# Generated by Django 5.2.10 on 2026-03-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_note_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_file',
            field=models.FileField(blank=True, null=True, upload_to='notes_files/'),
        ),
    ]
